export const SQL_TEMPLATE_QUERIES = {
  todoComplete: `-- Create todos table
CREATE TABLE todos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  completed BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Insert sample data
INSERT INTO todos (title, description, completed) VALUES
  ('Buy groceries', 'Milk, eggs, bread, and vegetables', FALSE),
  ('Finish project', 'Complete the SQL template feature', TRUE),
  ('Call mom', 'Remember to call mom this weekend', FALSE),
  ('Workout', 'Go to the gym for 30 minutes', FALSE);

-- Create indexes for performance
CREATE INDEX idx_todos_title ON todos(title);
CREATE INDEX idx_todos_completed ON todos(completed);
CREATE INDEX idx_todos_created_at ON todos(created_at);`,

  usersUuidComplete: `-- Create users table with UUID primary key
CREATE TABLE users (
  id UUID PRIMARY KEY DEFAULT uuidv7(),
  username VARCHAR(50) UNIQUE NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  first_name VARCHAR(100),
  last_name VARCHAR(100),
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Insert sample data
INSERT INTO users (username, email, password_hash, first_name, last_name) VALUES
  ('john_doe', 'john@example.com', 'hashed_password_1', 'John', 'Doe'),
  ('jane_smith', 'jane@example.com', 'hashed_password_2', 'Jane', 'Smith'),
  ('bob_wilson', 'bob@example.com', 'hashed_password_3', 'Bob', 'Wilson');

-- Create indexes for performance
CREATE INDEX idx_users_username ON users(username);
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_active ON users(is_active);`,

  postsComplete: `-- Create posts table
CREATE TABLE posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  content TEXT,
  author_id UUID REFERENCES users(id),
  status VARCHAR(20) DEFAULT 'draft',
  published_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Insert sample data
INSERT INTO posts (title, content, author_id, status, published_at) VALUES
  ('My First Blog Post', 'This is the content of my very first blog post. I''m excited to start writing!', 
   (SELECT id FROM users WHERE username = 'john_doe'), 'published', now()),
  ('SQL Tips and Tricks', 'Learn some amazing SQL techniques that will make your life easier.', 
   (SELECT id FROM users WHERE username = 'jane_smith'), 'published', now() - INTERVAL '1 day'),
  ('Draft Article', 'This is still a work in progress...', 
   (SELECT id FROM users WHERE username = 'john_doe'), 'draft', NULL),
  ('Database Design Best Practices', 'A comprehensive guide to designing efficient databases.', 
   (SELECT id FROM users WHERE username = 'bob_wilson'), 'published', now() - INTERVAL '2 days');

-- Create indexes for performance
CREATE INDEX idx_posts_title ON posts(title);
CREATE INDEX idx_posts_author_id ON posts(author_id);
CREATE INDEX idx_posts_status ON posts(status);
CREATE INDEX idx_posts_published_at ON posts(published_at);`,
} as const
