export const SQL_TEMPLATE_QUERIES = {
  todoComplete: `-- Create todos table
CREATE TABLE todos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  completed BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Insert sample data
INSERT INTO todos (title, description, completed) VALUES
  ('Buy groceries', 'Milk, eggs, bread, and vegetables', FALSE),
  ('Finish project', 'Complete the SQL template feature', TRUE),
  ('Call mom', 'Remember to call mom this weekend', FALSE),
  ('Workout', 'Go to the gym for 30 minutes', FALSE);

-- Create indexes for performance
CREATE INDEX idx_todos_title ON todos(title);
CREATE INDEX idx_todos_completed ON todos(completed);
CREATE INDEX idx_todos_created_at ON todos(created_at);`,

  usersUuidComplete: `-- Create users table with UUID primary key
CREATE TABLE users (
  id UUID PRIMARY KEY DEFAULT uuidv7(),
  username VARCHAR(50) UNIQUE NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  first_name VARCHAR(100),
  last_name VARCHAR(100),
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Insert sample data
INSERT INTO users (username, email, password_hash, first_name, last_name) VALUES
  ('john_doe', 'john@example.com', 'hashed_password_1', 'John', 'Doe'),
  ('jane_smith', 'jane@example.com', 'hashed_password_2', 'Jane', 'Smith'),
  ('bob_wilson', 'bob@example.com', 'hashed_password_3', 'Bob', 'Wilson');

-- Create indexes for performance
CREATE INDEX idx_users_username ON users(username);
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_active ON users(is_active);`,

  postsComplete: `-- Create posts table
CREATE TABLE posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  content TEXT,
  author_id UUID REFERENCES users(id),
  status VARCHAR(20) DEFAULT 'draft',
  published_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Insert sample data
INSERT INTO posts (title, content, author_id, status, published_at) VALUES
  ('My First Blog Post', 'This is the content of my very first blog post. I''m excited to start writing!', 
   (SELECT id FROM users WHERE username = 'john_doe'), 'published', now()),
  ('SQL Tips and Tricks', 'Learn some amazing SQL techniques that will make your life easier.', 
   (SELECT id FROM users WHERE username = 'jane_smith'), 'published', now() - INTERVAL '1 day'),
  ('Draft Article', 'This is still a work in progress...', 
   (SELECT id FROM users WHERE username = 'john_doe'), 'draft', NULL),
  ('Database Design Best Practices', 'A comprehensive guide to designing efficient databases.', 
   (SELECT id FROM users WHERE username = 'bob_wilson'), 'published', now() - INTERVAL '2 days');

-- Create indexes for performance
CREATE INDEX idx_posts_title ON posts(title);
CREATE INDEX idx_posts_author_id ON posts(author_id);
CREATE INDEX idx_posts_status ON posts(status);
CREATE INDEX idx_posts_published_at ON posts(published_at);`,

  uuidComplete: `-- Create a comprehensive UUID-based schema
-- Users table with UUID primary key
CREATE TABLE users (
  id UUID PRIMARY KEY DEFAULT uuidv7(),
  username VARCHAR(50) UNIQUE NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  first_name VARCHAR(100),
  last_name VARCHAR(100),
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Profiles table with UUID foreign key
CREATE TABLE profiles (
  id UUID PRIMARY KEY DEFAULT uuidv7(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  bio TEXT,
  avatar_url VARCHAR(500),
  website VARCHAR(255),
  location VARCHAR(100),
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Posts table with UUID author reference
CREATE TABLE posts (
  id UUID PRIMARY KEY DEFAULT uuidv7(),
  title VARCHAR(255) NOT NULL,
  content TEXT,
  author_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  status VARCHAR(20) DEFAULT 'draft',
  published_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Comments table with UUID references
CREATE TABLE comments (
  id UUID PRIMARY KEY DEFAULT uuidv7(),
  post_id UUID NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  author_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Insert sample data
INSERT INTO users (username, email, password_hash, first_name, last_name) VALUES
  ('john_doe', 'john@example.com', 'hashed_password_1', 'John', 'Doe'),
  ('jane_smith', 'jane@example.com', 'hashed_password_2', 'Jane', 'Smith'),
  ('bob_wilson', 'bob@example.com', 'hashed_password_3', 'Bob', 'Wilson');

INSERT INTO profiles (user_id, bio, website, location) VALUES
  ((SELECT id FROM users WHERE username = 'john_doe'), 'Software developer passionate about PostgreSQL', 'https://johndoe.dev', 'San Francisco'),
  ((SELECT id FROM users WHERE username = 'jane_smith'), 'Data scientist and tech writer', 'https://janesmith.io', 'New York'),
  ((SELECT id FROM users WHERE username = 'bob_wilson'), 'DevOps engineer and cloud architect', 'https://bobwilson.tech', 'Austin');

INSERT INTO posts (title, content, author_id, status, published_at) VALUES
  ('Getting Started with UUIDv7 in PostgreSQL', 'UUIDv7 combines the benefits of UUIDs with timestamp ordering...', 
   (SELECT id FROM users WHERE username = 'john_doe'), 'published', now() - INTERVAL '2 days'),
  ('Advanced Database Indexing Strategies', 'Learn how to optimize your database performance...', 
   (SELECT id FROM users WHERE username = 'jane_smith'), 'published', now() - INTERVAL '1 day'),
  ('Draft: Microservices Architecture', 'This post explores microservices design patterns...', 
   (SELECT id FROM users WHERE username = 'bob_wilson'), 'draft', NULL);

INSERT INTO comments (post_id, author_id, content) VALUES
  ((SELECT id FROM posts WHERE title = 'Getting Started with UUIDv7 in PostgreSQL'), 
   (SELECT id FROM users WHERE username = 'jane_smith'), 'Great article! UUIDv7 is a game changer.'),
  ((SELECT id FROM posts WHERE title = 'Getting Started with UUIDv7 in PostgreSQL'), 
   (SELECT id FROM users WHERE username = 'bob_wilson'), 'I''ve been using UUIDv7 in production and it works great.'),
  ((SELECT id FROM posts WHERE title = 'Advanced Database Indexing Strategies'), 
   (SELECT id FROM users WHERE username = 'john_doe'), 'Very comprehensive guide, thank you!');

-- Create indexes for optimal performance
CREATE INDEX idx_users_username ON users(username);
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_active ON users(is_active);

CREATE INDEX idx_profiles_user_id ON profiles(user_id);

CREATE INDEX idx_posts_author_id ON posts(author_id);
CREATE INDEX idx_posts_status ON posts(status);
CREATE INDEX idx_posts_published_at ON posts(published_at);
CREATE INDEX idx_posts_created_at ON posts(created_at);

CREATE INDEX idx_comments_post_id ON comments(post_id);
CREATE INDEX idx_comments_author_id ON comments(author_id);
CREATE INDEX idx_comments_created_at ON comments(created_at);`,
} as const
