export const SQL_TEMPLATE_QUERIES = {
  todoComplete: `-- Create categories table
CREATE TABLE todo_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  color VARCHAR(20),
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Create todos table
CREATE TABLE todos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id BIGINT REFERENCES todo_categories(id) ON DELETE SET NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  completed BOOLEAN DEFAULT FALSE,
  due_date TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Create tags table
CREATE TABLE todo_tags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) UNIQUE NOT NULL
);

-- Create todo_tags_map table (many-to-many)
CREATE TABLE todo_tags_map (
  todo_id BIGINT REFERENCES todos(id) ON DELETE CASCADE,
  tag_id BIGINT REFERENCES todo_tags(id) ON DELETE CASCADE,
  PRIMARY KEY (todo_id, tag_id)
);

-- Insert sample data
INSERT INTO todo_categories (name, color) VALUES
  ('Personal', '#3b82f6'),
  ('Work', '#ef4444'),
  ('Health', '#10b981');

INSERT INTO todos (category_id, title, description, completed, due_date) VALUES
  ((SELECT id FROM todo_categories WHERE name = 'Personal'), 'Buy groceries', 'Milk, eggs, bread', FALSE, now() + INTERVAL '1 day'),
  ((SELECT id FROM todo_categories WHERE name = 'Work'), 'Finish project', 'Complete the SQL template feature', TRUE, now() - INTERVAL '1 day'),
  ((SELECT id FROM todo_categories WHERE name = 'Health'), 'Workout', 'Go to the gym for 30 minutes', FALSE, now());

INSERT INTO todo_tags (name) VALUES ('urgent'), ('home'), ('office');

INSERT INTO todo_tags_map (todo_id, tag_id) VALUES
  ((SELECT id FROM todos WHERE title = 'Buy groceries'), (SELECT id FROM todo_tags WHERE name = 'home')),
  ((SELECT id FROM todos WHERE title = 'Finish project'), (SELECT id FROM todo_tags WHERE name = 'urgent')),
  ((SELECT id FROM todos WHERE title = 'Finish project'), (SELECT id FROM todo_tags WHERE name = 'office'));

-- Create indexes for performance
CREATE INDEX idx_todos_category ON todos(category_id);
CREATE INDEX idx_todos_completed ON todos(completed);
CREATE INDEX idx_todos_due_date ON todos(due_date);`,

  usersUuidComplete: `-- Create roles table
CREATE TABLE user_roles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(50) UNIQUE NOT NULL,
  description TEXT,
  permissions JSONB DEFAULT '[]'::jsonb
);

-- Create users table
CREATE TABLE users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  role_id UUID REFERENCES user_roles(id) ON DELETE SET NULL,
  username VARCHAR(50) UNIQUE NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  first_name VARCHAR(100),
  last_name VARCHAR(100),
  is_active BOOLEAN DEFAULT TRUE,
  last_login_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Create sessions table
CREATE TABLE user_sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  token VARCHAR(255) UNIQUE NOT NULL,
  ip_address INET,
  user_agent TEXT,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Insert sample data
INSERT INTO user_roles (name, description, permissions) VALUES
  ('admin', 'Administrator with full access', '["all"]'),
  ('editor', 'Can edit content', '["read", "write"]'),
  ('user', 'Standard user', '["read"]');

INSERT INTO users (role_id, username, email, password_hash, first_name, last_name) VALUES
  ((SELECT id FROM user_roles WHERE name = 'admin'), 'admin_john', 'admin@example.com', 'hash1', 'John', 'Admin'),
  ((SELECT id FROM user_roles WHERE name = 'editor'), 'editor_jane', 'jane@example.com', 'hash2', 'Jane', 'Editor'),
  ((SELECT id FROM user_roles WHERE name = 'user'), 'user_bob', 'bob@example.com', 'hash3', 'Bob', 'User');

-- Create indexes for performance
CREATE INDEX idx_users_role ON users(role_id);
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_active ON users(is_active);
CREATE INDEX idx_sessions_user ON user_sessions(user_id);
CREATE INDEX idx_sessions_token ON user_sessions(token);`,

  postsComplete: `-- Create authors table
CREATE TABLE authors (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  bio TEXT,
  avatar_url VARCHAR(500),
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Create posts table
CREATE TABLE posts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title VARCHAR(255) NOT NULL,
  slug VARCHAR(255) UNIQUE NOT NULL,
  content TEXT,
  author_id UUID REFERENCES authors(id) ON DELETE CASCADE,
  status VARCHAR(20) DEFAULT 'draft',
  published_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Create tags table
CREATE TABLE tags (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(50) UNIQUE NOT NULL,
  slug VARCHAR(50) UNIQUE NOT NULL
);

-- Create post_tags table
CREATE TABLE post_tags (
  post_id UUID REFERENCES posts(id) ON DELETE CASCADE,
  tag_id UUID REFERENCES tags(id) ON DELETE CASCADE,
  PRIMARY KEY (post_id, tag_id)
);

-- Create comments table
CREATE TABLE comments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  post_id UUID REFERENCES posts(id) ON DELETE CASCADE,
  author_id UUID REFERENCES authors(id) ON DELETE SET NULL,
  content TEXT NOT NULL,
  is_approved BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Insert sample authors
INSERT INTO authors (name, email, bio) VALUES
  ('John Doe', 'john@example.com', 'Tech writer and blogger'),
  ('Jane Smith', 'jane@example.com', 'Full-stack developer');

-- Insert sample tags
INSERT INTO tags (name, slug) VALUES
  ('Technology', 'technology'),
  ('Database', 'database'),
  ('Web Development', 'web-development');

-- Insert sample posts
INSERT INTO posts (title, slug, content, author_id, status, published_at) VALUES
  ('My First Blog Post', 'my-first-blog-post', 'Content here...', (SELECT id FROM authors WHERE email = 'john@example.com'), 'published', now()),
  ('SQL Tips', 'sql-tips', 'Great SQL tips...', (SELECT id FROM authors WHERE email = 'jane@example.com'), 'published', now() - INTERVAL '1 day');

-- Create indexes
CREATE INDEX idx_posts_author ON posts(author_id);
CREATE INDEX idx_posts_status ON posts(status);
CREATE INDEX idx_posts_published ON posts(published_at);
CREATE INDEX idx_comments_post ON comments(post_id);`,

  ecommerceBasic: `-- Create product_categories table
CREATE TABLE product_categories (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(100) NOT NULL,
  description TEXT,
  parent_id UUID REFERENCES product_categories(id),
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Create products table
CREATE TABLE products (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  category_id UUID REFERENCES product_categories(id) ON DELETE SET NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  price DECIMAL(10,2) NOT NULL,
  sku VARCHAR(100) UNIQUE NOT NULL,
  stock_quantity INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Create product_reviews table
CREATE TABLE product_reviews (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id UUID REFERENCES products(id) ON DELETE CASCADE,
  customer_id UUID, -- Would reference users table in a real system
  rating INTEGER CHECK (rating >= 1 AND rating <= 5),
  review_text TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Create orders table
CREATE TABLE orders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_number VARCHAR(50) UNIQUE NOT NULL,
  customer_email VARCHAR(255) NOT NULL,
  total_amount DECIMAL(10,2) NOT NULL,
  status VARCHAR(20) DEFAULT 'pending',
  shipping_address JSONB,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Create order_items table
CREATE TABLE order_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id UUID REFERENCES orders(id) ON DELETE CASCADE,
  product_id UUID REFERENCES products(id) ON DELETE RESTRICT,
  quantity INTEGER NOT NULL,
  unit_price DECIMAL(10,2) NOT NULL,
  total_price DECIMAL(10,2) NOT NULL
);

-- Insert sample categories
INSERT INTO product_categories (name, description) VALUES
  ('Electronics', 'Electronic devices'),
  ('Clothing', 'Apparel');

-- Insert sample products
INSERT INTO products (category_id, name, price, sku, stock_quantity) VALUES
  ((SELECT id FROM product_categories WHERE name = 'Electronics'), 'Laptop Pro', 1299.99, 'LP-001', 50),
  ((SELECT id FROM product_categories WHERE name = 'Clothing'), 'T-Shirt', 19.99, 'TS-001', 100);

-- Create indexes
CREATE INDEX idx_products_category ON products(category_id);
CREATE INDEX idx_products_sku ON products(sku);
CREATE INDEX idx_reviews_product ON product_reviews(product_id);
CREATE INDEX idx_orders_customer ON orders(customer_email);
CREATE INDEX idx_order_items_order ON order_items(order_id);`,

  analyticsEvents: `-- Create properties schema table
CREATE TABLE event_schemas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_name VARCHAR(100) UNIQUE NOT NULL,
  schema_definition JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Create users table for analytics
CREATE TABLE analytics_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  anonymous_id VARCHAR(255) UNIQUE,
  identified_id VARCHAR(255) UNIQUE,
  first_seen TIMESTAMPTZ DEFAULT now(),
  last_seen TIMESTAMPTZ DEFAULT now(),
  properties JSONB,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Create user_sessions table
CREATE TABLE user_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES analytics_users(id) ON DELETE CASCADE,
  session_token VARCHAR(255) UNIQUE NOT NULL,
  started_at TIMESTAMPTZ DEFAULT now(),
  ended_at TIMESTAMPTZ
);

-- Create events table
CREATE TABLE events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  schema_id BIGINT REFERENCES event_schemas(id),
  user_id BIGINT REFERENCES analytics_users(id) ON DELETE SET NULL,
  session_id BIGINT REFERENCES user_sessions(id) ON DELETE SET NULL,
  properties JSONB,
  timestamp TIMESTAMPTZ DEFAULT now(),
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Insert sample data
INSERT INTO analytics_users (anonymous_id, properties) VALUES
  ('anon_123', '{"browser": "Chrome", "os": "Windows"}'),
  ('anon_456', '{"browser": "Safari", "os": "macOS"}');

INSERT INTO user_sessions (user_id, session_token) VALUES
  ((SELECT id FROM analytics_users WHERE anonymous_id = 'anon_123'), 'sess_abc'),
  ((SELECT id FROM analytics_users WHERE anonymous_id = 'anon_456'), 'sess_def');

INSERT INTO event_schemas (event_name, schema_definition) VALUES
  ('page_view', '{"type": "object", "properties": {"url": {"type": "string"}}}');

-- Create indexes
CREATE INDEX idx_analytics_users_anon ON analytics_users(anonymous_id);
CREATE INDEX idx_analytics_users_ident ON analytics_users(identified_id);
CREATE INDEX idx_events_user ON events(user_id);
CREATE INDEX idx_events_session ON events(session_id);
CREATE INDEX idx_events_timestamp ON events(timestamp);
CREATE INDEX idx_events_properties ON events USING GIN(properties);`
} as const
