export const SQL_TEMPLATE_QUERIES = {
  todoComplete: `-- Create todos table
CREATE TABLE todos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  completed BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Insert sample data
INSERT INTO todos (title, description, completed) VALUES
  ('Buy groceries', 'Milk, eggs, bread, and vegetables', FALSE),
  ('Finish project', 'Complete the SQL template feature', TRUE),
  ('Call mom', 'Remember to call mom this weekend', FALSE),
  ('Workout', 'Go to the gym for 30 minutes', FALSE);

-- Create indexes for performance
CREATE INDEX idx_todos_title ON todos(title);
CREATE INDEX idx_todos_completed ON todos(completed);
CREATE INDEX idx_todos_created_at ON todos(created_at);`,

  usersUuidComplete: `-- Create users table with UUID primary key
CREATE TABLE users (
  id UUID PRIMARY KEY DEFAULT uuidv7(),
  username VARCHAR(50) UNIQUE NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  first_name VARCHAR(100),
  last_name VARCHAR(100),
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Insert sample data
INSERT INTO users (username, email, password_hash, first_name, last_name) VALUES
  ('john_doe', 'john@example.com', 'hashed_password_1', 'John', 'Doe'),
  ('jane_smith', 'jane@example.com', 'hashed_password_2', 'Jane', 'Smith'),
  ('bob_wilson', 'bob@example.com', 'hashed_password_3', 'Bob', 'Wilson');

-- Create indexes for performance
CREATE INDEX idx_users_username ON users(username);
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_active ON users(is_active);`,

  postsComplete: `-- Create authors table
CREATE TABLE authors (
  id UUID PRIMARY KEY DEFAULT uuidv7(),
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  bio TEXT,
  avatar_url VARCHAR(500),
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Create posts table
CREATE TABLE posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  content TEXT,
  author_id UUID REFERENCES authors(id) ON DELETE CASCADE,
  status VARCHAR(20) DEFAULT 'draft',
  published_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Create comments table
CREATE TABLE comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT REFERENCES posts(id) ON DELETE CASCADE,
  author_id UUID REFERENCES authors(id) ON DELETE SET NULL,
  content TEXT NOT NULL,
  is_approved BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Insert sample authors
INSERT INTO authors (name, email, bio) VALUES
  ('John Doe', 'john@example.com', 'Tech writer and blogger with 10+ years of experience'),
  ('Jane Smith', 'jane@example.com', 'Full-stack developer and open source enthusiast'),
  ('Bob Wilson', 'bob@example.com', 'Database architect and performance optimization expert');

-- Insert sample posts
INSERT INTO posts (title, content, author_id, status, published_at) VALUES
  ('My First Blog Post', 'This is the content of my very first blog post. I''m excited to start writing!', 
   (SELECT id FROM authors WHERE email = 'john@example.com'), 'published', now()),
  ('SQL Tips and Tricks', 'Learn some amazing SQL techniques that will make your life easier.', 
   (SELECT id FROM authors WHERE email = 'jane@example.com'), 'published', now() - INTERVAL '1 day'),
  ('Draft Article', 'This is still a work in progress...', 
   (SELECT id FROM authors WHERE email = 'john@example.com'), 'draft', NULL),
  ('Database Design Best Practices', 'A comprehensive guide to designing efficient databases.', 
   (SELECT id FROM authors WHERE email = 'bob@example.com'), 'published', now() - INTERVAL '2 days');

-- Insert sample comments
INSERT INTO comments (post_id, author_id, content, is_approved) VALUES
  ((SELECT id FROM posts WHERE title = 'My First Blog Post'), 
   (SELECT id FROM authors WHERE email = 'jane@example.com'), 
   'Great first post! Looking forward to more content.', TRUE),
  ((SELECT id FROM posts WHERE title = 'SQL Tips and Tricks'), 
   (SELECT id FROM authors WHERE email = 'bob@example.com'), 
   'Very helpful tips, especially the indexing strategies!', TRUE),
  ((SELECT id FROM posts WHERE title = 'SQL Tips and Tricks'), 
   (SELECT id FROM authors WHERE email = 'john@example.com'), 
   'Could you add more examples for complex joins?', FALSE);

-- Create indexes for performance
CREATE INDEX idx_authors_email ON authors(email);
CREATE INDEX idx_authors_active ON authors(is_active);

CREATE INDEX idx_posts_title ON posts(title);
CREATE INDEX idx_posts_author_id ON posts(author_id);
CREATE INDEX idx_posts_status ON posts(status);
CREATE INDEX idx_posts_published_at ON posts(published_at);

CREATE INDEX idx_comments_post_id ON comments(post_id);
CREATE INDEX idx_comments_author_id ON comments(author_id);
CREATE INDEX idx_comments_approved ON comments(is_approved);
CREATE INDEX idx_comments_created_at ON comments(created_at);`,

  ecommerceBasic: `-- Create products table
CREATE TABLE products (
  id UUID PRIMARY KEY DEFAULT uuidv7(),
  name VARCHAR(255) NOT NULL,
  description TEXT,
  price DECIMAL(10,2) NOT NULL,
  sku VARCHAR(100) UNIQUE NOT NULL,
  stock_quantity INTEGER DEFAULT 0,
  category_id UUID,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Create categories table
CREATE TABLE categories (
  id UUID PRIMARY KEY DEFAULT uuidv7(),
  name VARCHAR(100) NOT NULL,
  description TEXT,
  parent_id UUID REFERENCES categories(id),
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Create orders table
CREATE TABLE orders (
  id UUID PRIMARY KEY DEFAULT uuidv7(),
  order_number VARCHAR(50) UNIQUE NOT NULL,
  customer_email VARCHAR(255) NOT NULL,
  total_amount DECIMAL(10,2) NOT NULL,
  status VARCHAR(20) DEFAULT 'pending',
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Create order_items table
CREATE TABLE order_items (
  id UUID PRIMARY KEY DEFAULT uuidv7(),
  order_id UUID REFERENCES orders(id) ON DELETE CASCADE,
  product_id UUID REFERENCES products(id) ON DELETE RESTRICT,
  quantity INTEGER NOT NULL,
  unit_price DECIMAL(10,2) NOT NULL,
  total_price DECIMAL(10,2) NOT NULL
);

-- Insert sample categories
INSERT INTO categories (name, description) VALUES
  ('Electronics', 'Electronic devices and gadgets'),
  ('Clothing', 'Apparel and accessories'),
  ('Books', 'Books and educational materials');

-- Insert sample products
INSERT INTO products (name, description, price, sku, stock_quantity, category_id) VALUES
  ('Laptop Pro', 'High-performance laptop for professionals', 1299.99, 'LP-001', 50, (SELECT id FROM categories WHERE name = 'Electronics')),
  ('Wireless Mouse', 'Ergonomic wireless mouse', 29.99, 'WM-002', 200, (SELECT id FROM categories WHERE name = 'Electronics')),
  ('Cotton T-Shirt', 'Comfortable cotton t-shirt', 19.99, 'CT-003', 100, (SELECT id FROM categories WHERE name = 'Clothing'));

-- Create indexes for performance
CREATE INDEX idx_products_category ON products(category_id);
CREATE INDEX idx_products_sku ON products(sku);
CREATE INDEX idx_products_active ON products(is_active);
CREATE INDEX idx_orders_status ON orders(status);
CREATE INDEX idx_orders_created_at ON orders(created_at);
CREATE INDEX idx_order_items_order ON order_items(order_id);
CREATE INDEX idx_order_items_product ON order_items(product_id);`,

  analyticsEvents: `-- Create events table for analytics
CREATE TABLE events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type VARCHAR(50) NOT NULL,
  user_id UUID,
  session_id VARCHAR(255),
  properties JSONB,
  timestamp TIMESTAMPTZ DEFAULT now(),
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Create users table for analytics
CREATE TABLE analytics_users (
  id UUID PRIMARY KEY DEFAULT uuidv7(),
  anonymous_id VARCHAR(255) UNIQUE,
  identified_id VARCHAR(255) UNIQUE,
  first_seen TIMESTAMPTZ DEFAULT now(),
  last_seen TIMESTAMPTZ DEFAULT now(),
  properties JSONB,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Insert sample events
INSERT INTO events (event_type, user_id, session_id, properties) VALUES
  ('page_view', (SELECT id FROM analytics_users LIMIT 1), 'sess_001', '{"page": "/home", "referrer": "google"}'),
  ('button_click', (SELECT id FROM analytics_users LIMIT 1), 'sess_001', '{"button": "signup", "location": "header"}'),
  ('form_submit', (SELECT id FROM analytics_users LIMIT 1), 'sess_001', '{"form": "contact", "fields": ["name", "email"]}');

-- Insert sample users
INSERT INTO analytics_users (anonymous_id, properties) VALUES
  ('anon_123', '{"browser": "Chrome", "os": "Windows", "country": "US"}'),
  ('anon_456', '{"browser": "Safari", "os": "macOS", "country": "UK"}');

-- Create indexes for performance
CREATE INDEX idx_events_type ON events(event_type);
CREATE INDEX idx_events_user ON events(user_id);
CREATE INDEX idx_events_session ON events(session_id);
CREATE INDEX idx_events_timestamp ON events(timestamp);
CREATE INDEX idx_events_properties ON events USING GIN(properties);
CREATE INDEX idx_analytics_users_anonymous ON analytics_users(anonymous_id);
CREATE INDEX idx_analytics_users_identified ON analytics_users(identified_id);
CREATE INDEX idx_analytics_users_properties ON analytics_users USING GIN(properties);`,
} as const
