/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as mainRouteRouteImport } from './routes/(main)/route'
import { Route as mainIndexRouteImport } from './routes/(main)/index'
import { Route as mainSqlIndexRouteImport } from './routes/(main)/sql/index'
import { Route as mainEditorIndexRouteImport } from './routes/(main)/editor/index'

const mainRouteRoute = mainRouteRouteImport.update({
  id: '/(main)',
  getParentRoute: () => rootRouteImport,
} as any)
const mainIndexRoute = mainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainSqlIndexRoute = mainSqlIndexRouteImport.update({
  id: '/sql/',
  path: '/sql/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainEditorIndexRoute = mainEditorIndexRouteImport.update({
  id: '/editor/',
  path: '/editor/',
  getParentRoute: () => mainRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof mainIndexRoute
  '/editor': typeof mainEditorIndexRoute
  '/sql': typeof mainSqlIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof mainIndexRoute
  '/editor': typeof mainEditorIndexRoute
  '/sql': typeof mainSqlIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(main)': typeof mainRouteRouteWithChildren
  '/(main)/': typeof mainIndexRoute
  '/(main)/editor/': typeof mainEditorIndexRoute
  '/(main)/sql/': typeof mainSqlIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/editor' | '/sql'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/editor' | '/sql'
  id: '__root__' | '/(main)' | '/(main)/' | '/(main)/editor/' | '/(main)/sql/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  mainRouteRoute: typeof mainRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(main)': {
      id: '/(main)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/': {
      id: '/(main)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/sql/': {
      id: '/(main)/sql/'
      path: '/sql'
      fullPath: '/sql'
      preLoaderRoute: typeof mainSqlIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/editor/': {
      id: '/(main)/editor/'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof mainEditorIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
  }
}

interface mainRouteRouteChildren {
  mainIndexRoute: typeof mainIndexRoute
  mainEditorIndexRoute: typeof mainEditorIndexRoute
  mainSqlIndexRoute: typeof mainSqlIndexRoute
}

const mainRouteRouteChildren: mainRouteRouteChildren = {
  mainIndexRoute: mainIndexRoute,
  mainEditorIndexRoute: mainEditorIndexRoute,
  mainSqlIndexRoute: mainSqlIndexRoute,
}

const mainRouteRouteWithChildren = mainRouteRoute._addFileChildren(
  mainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  mainRouteRoute: mainRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
